### ISSUE TITLE
add hover effects to navbar and making it responsive

### ISSUE THREAD

**Issue by Janhvi52** [Riya14-dangra/COFFEE-SHOP#7] opened 2022-12-11 10:42 UTC
can you assign me this issue?

**Comment by Riya14-dangra** [comment] 2022-12-11 11:34
> can you assign me this issue?

first complete the previous one then i will assign this to you

**Comment by DHRUVKHANDELWAL00** [comment] 2022-12-11 13:51
hey @Riya14-dangra , can u assign me this issue ?

**Comment by himanshu1221** [comment] 2022-12-11 13:58
can u please assign this issue to me under KWoC22

**Comment by Riya14-dangra** [comment] 2022-12-11 14:29
> can you assign me this issue?

@Janhvi52 will you wish to work on this issue or I will assign it to someone else

**Comment by Janhvi52** [comment] 2022-12-11 14:29
> > can you assign me this issue?
> 
> @Janhvi52 will you wish to work on this issue or I will assign it to someone else

Since I've mentioned it first, I would like to work on the issue

**Comment by Riya14-dangra** [comment] 2022-12-11 14:30
> > > can you assign me this issue?
> > 
> > 
> > @Janhvi52 will you wish to work on this issue or I will assign it to someone else
> 
> Since I've mentioned it first, I would like to work on the issue

Okay @Janhvi52 go for it

**Comment by Riya14-dangra** [comment] 2022-12-11 14:31
@himanshu1221 & @DHRUVKHANDELWAL00  create a new issue and start working on it

**Comment by himanshu1221** [comment] 2022-12-11 14:46
okay @Riya14-dangra

**Comment by SattyamSamania** [comment] 2022-12-16 04:08
Hey @Riya14-dangra if the issue is not solved can I work on this?

**Comment by Riya14-dangra** [comment] 2022-12-16 05:01
> Hey @Riya14-dangra if the issue is not solved can I work on this?

No @Janhvi52 is working on this you go for another one

**Comment by SattyamSamania** [comment] 2022-12-23 16:52
> > Hey @Riya14-dangra if the issue is not solved can I work on this?
> 
> No @Janhvi52 is working on this you go for another one

Hey @Riya14-dangra Can I start working now?

**Comment by Riya14-dangra** [comment] 2023-01-03 02:53
@Janhvi52 you can start working on it give me the status of your work within one day

**Closed as completed** 2023-01-04 02:09 UTC
